version: "2"
run:
  concurrency: 4
  issues-exit-code: 2
  tests: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - forcetypeassert
    - goconst
    - gocritic
    - godox
    - gosec
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      